# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2703a335-ce27-4fc0-a4b3-f67624910136";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AFC6-6C36";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/var/lib/containers/storage/overlay" =
    { device = "/var/lib/containers/storage/overlay";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/containers/storage/overlay-containers/6450073351fe61050f63e4f310fdad7418b859fa62679c91592acd64bdd6a6f8/userdata/shm" =
    { device = "shm";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/containers/storage/overlay/af87b214aec8160781e906854b701c2d12d3bebf3ddf86f7243aa614af20dacc/merged" =
    { device = "overlay";
      fsType = "overlay";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e88b4b68-13f7-4c78-85d2-7945e9834624"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
